### ISSUE TITLE
Menu bar stays

### ISSUE THREAD

**Issue by erwinhome** [TheLastProject/CSSBox#3]
Cssbox works great but the menu bar stays on top so the image is not completely visible neither is the "close" cross.
What can I do?

**Comment by TheLastProject** [comment]
I'm not quite sure what you mean, an image would be helpful. But my best guess is that some element has an even higher z-index than 999 and you should increase the z-index in cssbox.css

**Comment by erwinhome** [comment]
Wow!
I changed 999 in 9999 and that did the trick!
Thank you so much!

**Comment by jankapunkt** [comment]
Maybe there could be a little hint in the README? I could open a PR if you like.

**Comment by TheLastProject** [comment]
May make most sense to just increase the z-index to an even higher number. As far as I know it doesn't matter what the value is, just higher than other elements
